#version 450
layout(local_size_x = 256) in;

layout(std430, binding = 0) buffer Positions { vec4 positions[]; };
layout(std430, binding = 1) buffer Velocities { vec4 velocities[]; };
layout(std430, binding = 2) readonly buffer ForceVelocity { vec4 forceVelocity[]; };
layout(std140, binding = 5) uniform Params {
  vec4 gravity; vec4 boundsSize;
  float deltaT; float smoothingRadius; float particleMass; float targetDensity;
  float pressureMultiplier; float viscosityStrength; float collisionDamping;
  float spikyPow2Scale; float spikyPow2GradScale; float poly6Scale;
  uint numParticles; float epsilon; uvec4 grid;
} P;
layout(std430, binding = 9) readonly buffer SortedPos { vec4 sortedPos[]; };
void main() {
  uint idx = gl_GlobalInvocationID.x;
  if (idx >= P.numParticles) return;

  vec3 velocity = forceVelocity[idx].xyz;

  vec3 position = sortedPos[idx].xyz + velocity * P.deltaT;
  vec3 halfBounds = 0.5 * P.boundsSize.xyz;
  for (int axis = 0; axis < 3; ++axis) {
    if (abs(position[axis]) > halfBounds[axis]) {
      position[axis] = halfBounds[axis] * sign(position[axis]);
      velocity[axis] *= -P.collisionDamping;
    }
  }

  positions[idx] = vec4(position, 0.0);
  velocities[idx] = vec4(velocity, 0.0);
}
