#version 450
layout(local_size_x = 256) in;

layout(std140, binding = 5) uniform Params {
  vec4 gravity;
  vec4 boundsSize;
  float deltaT;
  float smoothingRadius;
  float particleMass;
  float targetDensity;
  float pressureMultiplier;
  float viscosityStrength;
  float collisionDamping;
  float densityKernelScale;
  float pressureGradientKernelScale;
  float viscosityKernelScale;
  uint numParticles;
  float epsilon;
  uvec4 grid;
} P;
layout(std430, binding = 8) buffer StartIndices { uint startIndices[]; };

void main() {
  uint i = gl_GlobalInvocationID.x;
  if (i < P.grid.w) startIndices[i] = 0xffffffffu;
}
