#version 450
#extension GL_GOOGLE_include_directive : require

layout(local_size_x = 256) in;

#include "sph_params.glsl"

layout(std430, binding = 6) readonly buffer SpatialKeys { uint spatialKeys[]; };
layout(std430, binding = 8) buffer StartIndices { uint startIndices[]; };
layout(std430, binding = 13) buffer EndIndices { uint endIndices[]; };

// keys are sorted
void main() {
  uint i = gl_GlobalInvocationID.x;
  if (i >= P.numParticles) return;

  uint key = spatialKeys[i];
  uint prev = (i == 0u) ? EMPTY_CELL : spatialKeys[i - 1u];
  if (key != prev) startIndices[key] = i;
  uint next = (i + 1u == P.numParticles) ? EMPTY_CELL : spatialKeys[i + 1u];
  if (key != next) endIndices[key] = i + 1u;
}
