#version 450
layout(local_size_x = 256) in;

layout(std140, binding = 5) uniform Params {
  vec4 gravity;
  vec4 boundsSize;
  float deltaT;
  float smoothingRadius;
  float particleMass;
  float targetDensity;
  float pressureMultiplier;
  float viscosityStrength;
  float collisionDamping;
  float densityKernelScale;
  float pressureGradientKernelScale;
  float viscosityKernelScale;
  uint numParticles;
  float epsilon;
  uvec4 grid;
} P;
layout(std430, binding = 6) readonly buffer SpatialKeys { uint spatialKeys[]; };
layout(std430, binding = 8) buffer StartIndices { uint startIndices[]; };
layout(std430, binding = 13) buffer EndIndices { uint endIndices[]; };

void main() {
  uint i = gl_GlobalInvocationID.x;
  if (i >= P.numParticles) return;
  uint key = spatialKeys[i];
  uint prev = (i == 0u) ? 0xffffffffu : spatialKeys[i - 1u];
  if (key != prev) startIndices[key] = i;
  uint next = (i + 1u == P.numParticles) ? 0xffffffffu
                                         : spatialKeys[i + 1u];
  if (key != next) endIndices[key] = i + 1u;
}
